---
output:
  pdf_document: default
  html_document: default
---
```{r}
library(bayesfam)
# global RMD settings
x <- seq(from=-8, to=8, length.out=1000)
col1 <- 'red'
col2 <- 'yellow'
col3 <- 'blue'
print("Showcase of different qualitative continuous unbound distributions")
```
```{r}
normal_narrow <- c(0, 2/3)
normal_broad <- c(0, 3/2)

plot(x, dnorm(x, normal_narrow[1], normal_narrow[2]), type='l', col=col1,
     ylab='different qualitative normal PDFs')
lines(x, dnorm(x, normal_broad[1], normal_broad[2]), type='l', col=col2)
```
```{r}
t_highTail <- c(0, 1)
t_lowTail <- c(0, 10)
t_skewed <- c(5, 10)
# usually, mu then shape. In dt, it is reversed.
plot(x, dt(x, t_lowTail[2], t_lowTail[1]), type='l', col=col2, 
      ylab='different qualitative student-t PDFs')
lines(x, dt(x, t_highTail[2], t_highTail[1]), type='l', col=col1)
lines(x, dt(x+5.5, t_skewed[2], t_skewed[1]), type='l', col=col3)
```
```{r}
sn_left <- c(0, 1, 10)
sn_geometric <- c(0, 1, 0)

plot(x, brms::dskew_normal(x, mu=sn_left[1], sigma=sn_left[2], alpha=sn_left[3]), 
     type='l', col=col1, ylab='different qualitative skew-normal PDFs')
lines(x, brms::dskew_normal(x, mu=sn_geometric[1], sigma=sn_geometric[2], 
                            alpha=sn_geometric[3]), type='l', col=col2)
```
```{r}
gn_normal <- c(0, 1, 2)
gn_broad <- c(0, 1, 8)
sn_narrow <- c(0, 1, 1)

plot(x, dgeneralized_normal(x, mu=gn_normal[1], sigma=gn_normal[2], 
                            beta=gn_normal[3]), type='l', col=col1, 
                            ylab='different qualitative generalized-normal PDFs')
lines(x, dgeneralized_normal(x, mu=gn_broad[1], sigma=gn_broad[2], 
                             beta=gn_broad[3]), type='l', col=col2)
lines(x, dgeneralized_normal(x, mu=sn_narrow[1], sigma=sn_narrow[2], 
                             beta=sn_narrow[3]), type='l', col=col3)
```
```{r}
al_sym <- c(0, 1, 0.5)
al_left <- c(-1, 1, 0.25)
#al_right <- c(0, 1, 0.75)

plot(x, brms::dasym_laplace(x, mu=al_sym[1], sigma=al_sym[2], 
                            quantile=al_sym[3]), type='l', col=col1, 
                            ylab='different qualitative asymmetric-Laplace PDFs')
lines(x, brms::dasym_laplace(x, mu=al_left[1], sigma=al_left[2], 
                             quantile=al_left[3]), type='l', col=col2)
```
```{r}
exg_lightlySkewed <- c(0, 1, 0.1)
exg_heavilySkewed <- c(0, 1, 2)

plot(x, brms::dexgaussian(x, mu=exg_lightlySkewed[1], sigma=exg_lightlySkewed[2], 
                          beta=exg_lightlySkewed[3]), type='l', col=col1, 
                          ylab='different qualitative ExGauss PDFs')
lines(x, brms::dexgaussian(x, mu=exg_heavilySkewed[1], sigma=exg_heavilySkewed[2], 
                          beta=exg_heavilySkewed[3]), type='l', col=col2)
```
```{r}
gumbel_narrow <- c(0, 1)
gumbel_broad <- c(0, 1.5)

plot(x, dgumbel_mean(x+0.5, gumbel_narrow[1], gumbel_narrow[2]), type='l', col=col1,
     ylab='different qualitative gumbel PDFs')
lines(x, dnorm(x, gumbel_broad[1], gumbel_broad[2]), type='l', col=col2)
```

